### ISSUE TITLE
The meaning of "--alpha_on --omega_on --gamma_on --z_on" in command line

### ISSUE THREAD

**Issue by Hugo101** [haebeom-lee/l2b#1]
In the `main.py`, these four parameters are default `False`. So do we still need to add "--alpha_on --omega_on --gamma_on --z_on" in the command?

Also, I did not find where we use "--alpha_on, --z_on" in the `main.py` file.

When I follow the exact instruction of the experiment (CIFAR, SVHN), I have the following results: The results are similar to that of MAML, not better than Bayesian TAML. Do you have any ideas?

![image](https://user-images.githubusercontent.com/18361043/78469075-2c3bed00-76e3-11ea-91fc-d2e43e9fb9da.png)

**Comment by haebeom-lee** [comment]
Yes, you should **turn on the four variables for both meta-training and meta-testing**. Please see the below instructions (you can also see it from README.md):

Please let me know if you have the same results after turning on all the variables correctly.

Also, the flag of those four variables are used in **model.py** (line 108,126,138,144).

### Meta-training
```
$ python main.py \
  --gpu_id 0 \
  --savedir "./results/cifar/taml" --id_dataset 'cifar' --ood_dataset 'svhn' \
  --mode 'meta_train' --metabatch 4 --n_steps 5 --way 5 --max_shot 50 --query 15 \
  --n_train_iters 50000 --meta_lr 1e-3 \
  --alpha_on --omega_on --gamma_on --z_on
```

### Meta-testing
```
$ python main.py \
  --gpu_id 0 \
  --savedir "./results/cifar/taml" --id_dataset 'cifar' --ood_dataset 'svhn' \
  --mode 'meta_test' --metabatch 4 --n_steps 10 --way 5 --max_shot 50 --query 15 \
  --n_test_episodes 1000 \
  --alpha_on --omega_on --gamma_on --z_on --n_mc_samples 10
```

**Comment by Hugo101** [comment]
Thanks so much for your quick reply! It makes sense. Sorry for this so simple question!
